#!/bin/bash

############ The task of temperature
Temp_Task=70357		# 70°C CPU  (65316; 70357; 75118; .... )
Temp_WIFI=45000		# 70°C WIFI (70379)
Temp_DDR=50000		# 60°C DDR
Temp_Switch=60000	# 70°C Switch

Device=(DDR Wi-Fi Switch CPU)

Temp[1]=$((Temp_Task - Temp_WIFI))
Temp[2]=$((Temp_Task - Temp_DDR))
Temp[3]=$((Temp_Task - Temp_Switch))
Temp[4]=0

############ The task of factors of a regulator
K_Prop=300	# 50...720
K_Dif=90	# 10...100
K_FanOn=40	# The smallest value at the output pwm1 (gpio 18) control in which the fan is spinning.
		# You should choose a small margin +3...+5
Temp_Previous=$Temp_Task

############
while true ; do
Temp_Current=0
T[1]=$((Temp[1] + `cat /sys/class/hwmon/hwmon1/temp1_input`))
T[2]=$((Temp[2] + `cat /sys/class/hwmon/hwmon1/temp2_input`))
T[3]=$((Temp[3] + `cat /sys/class/hwmon/hwmon3/temp1_input`))
T[4]=`cat /sys/class/hwmon/hwmon2/temp1_input`


############ Choice of the greatest temperature
for ((i=1; i<${#T[*]}; i++)); do
T=$((T[$i]))

	if [ $T -gt $Temp_Current ]
		then
		Temp_Current=$T
		Numb=$i
	fi
#printf  $T\\t
done

############ Proportional part
Error=$((Temp_Current - Temp_Task))
FctrProp=$((Error / K_Prop))

############ Differential part
FctrDif=$(((Temp_Current - Temp_Previous) / K_Dif))

############ Reducing regulatory factor in the area of the set temperature ±0.476°C (476)
	if [ $Error -ge -476 -a $Error -le 476 ]
		then
		#FctrProp=$((FctrProp / 4))
		FctrDif=$((FctrDif / 3))
	fi

FanCtrl=$((FctrProp + FctrDif + FanCtrl))

########### Setting the working range of the fan
	if [ $FanCtrl -gt 255 ]
		then
                FanCtrl=255
	fi
	if [ $FanCtrl -lt $K_FanOn ]
		then
		Out_FanCtrl=0
		else
		Out_FanCtrl=$FanCtrl
	fi
	if [ $FanCtrl -lt $((K_FanOn - 4)) ]
		then
		FanCtrl=$((K_FanOn - 4))
	fi
	if [ $FanCtrl -ge 255 -a $Temp_Current -ge $((Temp_Task + 3000)) ]
		then
		echo "`date`: High temperature "${Device[$Numb-1]}" +"$(echo "scale=1; ($Temp_Current-${Temp[$Numb]})/1000" | bc)"°C"  >> /root/overheat.log
	fi

########### Out fan
echo $Out_FanCtrl > /sys/class/hwmon/hwmon0/pwm1
echo $Out_FanCtrl > /sys/class/leds/rango:amber:wps/brightness

###########
#cpu=`ps aux | awk '{s += $3} END {print s}'`
#printf "%s	%s	%s	%s	%s	%s\n" $FctrProp $FctrDif $Out_FanCtrl $Temp_Current $cpu
##########
Temp_Previous=$Temp_Current
FanCtrl_Previous=$FanCtrl
#Error_Previous=$Error
sleep 10
done
