#!/bin/bash

# Because WRT3200 does not have real-time clocks, when the router is started,
# the time and date are set by default from Debian. So in Debian 8 "Jessie",
# the default date is [1970-01-01], Debian 9 "Stretch"-[2016-11-03]. 
# Sometimes it happens that the NTP server cannot be synchronized the first time.
# To determine the relevance of the Adblock base, you must define the current
# date and compare it to the creation date of the existing base. To do this,
# you enter several times to synchronize the date.

### Synchronize system date and time
i=0
while [ $i -le 10 ] ; do
/etc/init.d/ntp restart
sleep 10

### Check the validity of the Blacklist base by date
filed=`stat /etc/adblock.blacklist |grep Modify`
filed=${filed:8:10}		# The date changed that the Adblock database
debd="2016-11-03"		# Date prior to synchronization with NTP server
curd=$(date "+%Y-%m-%d")	# Date after attempt to synchronize with NTP server
i=$((i + 1))

if [ "$curd" = "$debd" ]
	then continue		# Attempting to synchronize with NTP server
fi
if [ "$curd" = "$filed" -a "$debd" != "$filed" ]
	then exit		# adblock.blacklist no update required
	else break		# adblock.blacklist needs to update base
fi
done
if [ "$curd" = "$debd" ]
	then exit		# No sync, leave existing base adblock.blacklist
	else echo		# adblock.blacklist needs to update base
fi

echo 255 > /sys/class/leds/rango:amber:wan/brightness
cd /home/tmp

### Download and create the Blacklist base
out="/etc/adblock.blacklist"
in="tmp"
i=0
while read line ; do
addr=$line
	i=$((i+1))
	wget $addr --no-check-certificate -O hosts_list.$i
	sed -i "/^[#<:!_ .]/d" hosts_list.$i		#search '#<:!_ .' del
	sed -i "/#./d" hosts_list.$i			#search '#.'  del
	sed -i "/\x22/d" hosts_list.$i                  #search '"'   del
	sed -i "/\x28/d" hosts_list.$i			#search '('   del
	sed -i "/\x29/d" hosts_list.$i			#search ')'   del
	sed -i "/\x7B/d" hosts_list.$i			#search '{'   del
	sed -i "/\x7D/d" hosts_list.$i			#search '}'   del
	sed -i -e "s/||//g" hosts_list.$i		#search '||' replace ''
	sed -i -e "s/\^//g" hosts_list.$i		#search '^' replace ''
	sed -i -e "s/,/\n/g" hosts_list.$i		#search ',' replace '\n'
	sed -i -e "s/127.0.0.1//g" hosts_list.$i	#search '127.0.0.0' replace ''
	sed -i -e "s/0.0.0.0//g" hosts_list.$i		#search '0.0.0.0' replace ''
	sed -i -e "s/^[\t ]\{1,8\}//g" hosts_list.$i	#search 'tab' - '1...8' replace ''
	sed -i -e "s/\t\{1,8\}//g" hosts_list.$i	#search 'tab' - '1...8' replace ''
	sed -i -e "s/https://g" hosts_list.$i		#search 'https:' replace ''
	sed -i -e "s/http://g" hosts_list.$i		#search 'http:' replace ''
	sed -i -e "s/\x2F//g" hosts_list.$i		#search '/' replace ''
	sed -i -e "s/\x40//g" hosts_list.$i		#search '@' replace ''
	sed -i -e "s/\x7C//g" hosts_list.$i		#search "|" replace ''
#	sed -i "/^\.com/d" hosts_list.$i
	sed -i -e "s/^/127.0.0.1 /g" hosts_list.$i
cat hosts_list.$i >> $in
done < /etc/adblock.addr
rm -rf hosts_list.*

echo "#/ip dns static" > $out && cat $in  \
	| grep -v '^#' \
	| tr -d '\r' \
	| sed '$!N; /^\(.*\)\n\1$/!P; D' \
	| sort -u  >> $out && rm -f $in

### Removing from Blacklist database the Whitelist data
while read line ; do
#line="127.0.0.1 "$line
echo $line
	sed  "/$line/d" $out > /etc/adblock.tmp
	mv /etc/adblock.tmp $out
done < /etc/adblock.whitelist

wc -l $out
### Restart service DNSMASQ
/etc/init.d/dnsmasq restart

echo 0 > /sys/class/leds/rango:amber:wan/brightness
echo netdev > /sys/class/leds/rango:amber:wan/trigger
echo tap0 > /sys/class/leds/rango:amber:wan/device_name
echo 1 > /sys/class/leds/rango:amber:wan/rx
echo 1 > /sys/class/leds/rango:amber:wan/tx
